### PR TITLE
Fix broken TextHighlighter and Code block classifier (#8)

### LINKED ISSUE #8: TextHighlighter and Code block classifier are broken
This is my due to own ignorance of how the `IViewTaggerProvider` works, in the following snippet, `Instance` will be set multiple times, because VS will spawn each `TextHighlighter` for a `ITextView` and will break the highlighter and code block recognition.

https://github.com/Exafunction/CodeiumVisualStudio/blob/c182421989de8e7d5c4bead2215c293df5f68384/CodeiumVS/TextHighlighter.cs#L50C1-L53C21

To fix this: Add a static dictionary of `<ITextView, TextHighlighter>`

### PR DESCRIPTION
**Pull request by thedemons**
This PR fixes #8 

Summary:
- Added the `Utilities` namespace and moved TextHighlighter there
- Added the `MefProvider` class which provides MEF-imported components
- Added the `CodeAnalyzer` which provides code analysis functions
- New file `Extensions.cs` which should contain base types, interfaces, and classes when adding them in the future
- Removed the debug button

### CODE REVIEW

File: CodeiumVS/Utilities/Extensions.cs [hunk 1]
```diff
@@ -0,0 +1,30 @@
+﻿using Microsoft.VisualStudio.Text.Editor;
+using Microsoft.VisualStudio.TextManager.Interop;
+using System.Collections.Generic;
+
+namespace CodeiumVS.Utilities;
+
+internal abstract class TextViewExtension<T> where T : class
```
Comment (thedemons) [inline CodeiumVS/Utilities/Extensions.cs:7]: This class will be the base class for anything that is associated with a `ITextView`, it provides a `Dictionary<ITextView, T> Instances` and `T? GetInstance(ITextView hostView)` method which will get an instance of the derived class that is attached to the view.
